#! /usr/bin/env bash
source bashlib

icons=(
    [29]="Icon-Small.png"
    [50]="Icon-Small-50.png"
    [58]="Icon-Small@2x.png"
    [57]="Icon.png"
    [72]="Icon-72.png"
    [114]="Icon@2x.png"
)
cd "${0%/*}/../Images"

emit "Converting iTunesArtwork"
for size in "${!icons[@]}"; do
    file=${icons[size]}

    emit "$file ($size px)" --
        convert "iTunesArtwork.png" -resize "${size}x${size}" "$file"
    emit -$?
done
